server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Collect Docker container logs
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      # Parse Docker JSON logs
      - json:
          expressions:
            output: log
            stream: stream
            timestamp: time

      # Extract timestamp
      - timestamp:
          source: timestamp
          format: RFC3339Nano

      # Add container labels
      - labels:
          stream:

  # Collect system logs
  - job_name: syslog
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          __path__: /var/log/*log

  # Collect realm-specific logs
  - job_name: realm
    static_configs:
      - targets:
          - localhost
        labels:
          job: realm
          __path__: /var/log/realm/*.log