repos:
  - repo: local
    hooks:
      - id: docs-metadata-lint
        name: Docs metadata & attribution linter
        entry: python3 scripts/docs_metadata_lint.py docs
        language: system
        pass_filenames: false
