site_name: The Realm Codex (Unified)
site_description: A living grimoire joined with practical runbooks
theme:
  name: material
  language: en
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
    - search.suggest
    - toc.follow
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
nav:
  - Prologue: index.md
  - Lore:
    - Cosmology: lore/cosmology.md
    - Naming Rites: lore/naming-rites.md
    - Rituals (Runbooks): lore/rituals.md
  - Bestiary (Spirits):
    - {{SPIRIT_CLAUDE_TITLE}}: bestiary/claude.md
    - {{SPIRIT_CODEX_TITLE}}: bestiary/codex.md
    - {{SPIRIT_GEMINI_TITLE}}: bestiary/gemini.md
    - {{SPIRIT_LOCAL_TITLE}}: bestiary/local.md
  - Grimoire (Scripts):
    - Spellbook Index: grimoire/index.md
  - Sanctum (Security): sanctum/index.md
  - Apps of the Realm: apps/index.md
  - Practical Framework:
    - Core Philosophy: framework/core-philosophy.md
    - System Map: framework/system-map.md
    - Refactor Program: framework/refactor.md
    - Modularity: framework/modularity.md
  - Standards:
    - Naming Conventions: standards/naming-conventions.md
  - Chronicle (Ops Journal): chronicle.md
